export interface VideoEntry {
  title: string
  description?: string
  url: string
  type?: "youtube" | "loom"
  skillLevel?: "beginner" | "intermediate" | "pro"
}

export const videoDatabase: VideoEntry[] = [
  {
    title: "3 Exercises to Stabilize Elbow and Keep Ball Moving",
    description: "Starting at the END of the shot and working our way to the floor.",
    url: "https://youtu.be/hYXluVW72Dk",
    type: "youtube",
    skillLevel: "intermediate",
  },
  {
    title: "Ball Does Not Stop (KSS)",
    description: "Ball doesn't stop relative to the ground, but can stop relative to the body.",
    url: "https://youtu.be/iWHy9AgRVRw",
    type: "youtube",
    skillLevel: "beginner",
  },
  {
    title: "Stabilize The Shooting Elbow",
    description: "What it looks like stabilizing vs passing through the shooting elbow and how to progress towards it.",
    url: "https://youtu.be/hj6EwEzQo8s",
    type: "youtube",
    skillLevel: "beginner",
  },
  {
    title: "Guide Hand Positioning (KSS)",
    description: "How to position the guide hand early to avoid mistakes later.",
    url: "https://youtu.be/rOSPDRDqonE",
    type: "youtube",
    skillLevel: "beginner",
  },
  {
    title: "Jump Turns With Pass",
    url: "https://youtu.be/qY_fSx1833k",
    type: "youtube",
    skillLevel: "intermediate",
  },
  {
    title: "Catch and Shoot With Pass Fake",
    url: "https://youtu.be/0pOsjfBxN78",
    type: "youtube",
    skillLevel: "intermediate",
  },
  {
    title: "2 Dribble Jump Turns",
    url: "https://youtu.be/1OyTCKJyLMU",
    type: "youtube",
    skillLevel: "pro",
  },
  {
    title: "1 Dribble Jump Turns",
    url: "https://youtu.be/5k2hDRj0IjE",
    type: "youtube",
    skillLevel: "intermediate",
  },
  {
    title: "Foul Line to Elbow Dribble Spins",
    url: "https://youtu.be/smWw5_HlGJU",
    type: "youtube",
    skillLevel: "pro",
  },
  {
    title: "Outside Leg Catch and Drop",
    url: "https://youtu.be/i_iJpxA-hWk",
    type: "youtube",
    skillLevel: "intermediate",
  },
  {
    title: "Dribble Step Bounce Throughs",
    url: "https://youtu.be/KjmYJEZeYR8",
    type: "youtube",
  },
  {
    title: "Momentum Shots",
    url: "https://youtu.be/99H6Cl5Cwtk",
    type: "youtube",
  },
  {
    title: "Dribble Step Elbow Spins",
    url: "https://youtu.be/iw9OPOCwV5M",
    type: "youtube",
  },
  {
    title: "Ghost Screen Back Pedal",
    url: "https://youtu.be/E_6n_13DXYs",
    type: "youtube",
  },
  {
    title: "Transition Break to Wing",
    url: "https://youtu.be/wyUT3tuSyqQ",
    type: "youtube",
  },
  {
    title: "Steph Curry Transition Turns",
    url: "https://youtu.be/abL0TSxpeY0",
    type: "youtube",
  },
  {
    title: "Backpedal Catch and Shoot",
    url: "https://youtu.be/n1B1gmjphkg",
    type: "youtube",
  },
  {
    title: "Sprint into Slide to Corner",
    url: "https://youtu.be/NErEM4PZ8kQ",
    type: "youtube",
  },
  {
    title: "Sprint to Corner",
    url: "https://youtu.be/9jln-CVvo_0",
    type: "youtube",
  },
  {
    title: "Rollouts with Slides",
    url: "https://youtu.be/SqKUvO2WI_8",
    type: "youtube",
  },
  {
    title: "Rollouts",
    url: "https://youtu.be/EZAywAnDRC0",
    type: "youtube",
  },
  {
    title: "Catch and Shoot (Drop, Left Right, Right Left)",
    url: "https://youtu.be/RJ3fpWuERwA",
    type: "youtube",
  },
  {
    title: "Forward Backward Hop (1 Position)",
    url: "https://youtu.be/ZM7-WfP7f9c",
    type: "youtube",
  },
  {
    title: "Backward Forward Hop (1 Position)",
    url: "https://youtu.be/es4_W8WOElE",
    type: "youtube",
  },
  {
    title: "Backwards Hop (1 Position)",
    url: "https://youtu.be/e9PX1ej52aE",
    type: "youtube",
  },
  {
    title: "Forward Hop (1 Position)",
    url: "https://youtu.be/J1xJcNdWtlk",
    type: "youtube",
  },
  {
    title: "Wrist Flip Dribble",
    url: "https://youtu.be/CB4Au-e6v-U",
    type: "youtube",
  },
  {
    title: "Wrist Flip Spin Out",
    url: "https://youtu.be/DckkB_SLFek",
    type: "youtube",
  },
  {
    title: "Wrist Flip Hops",
    url: "https://youtu.be/_Of4VW6P6eA",
    type: "youtube",
  },
  {
    title: "Test: 100 3's",
    url: "https://youtu.be/0-hpgLnRCoI",
    type: "youtube",
  },
  {
    title: "Jab Series",
    url: "https://youtu.be/FbUSGDpcL3E",
    type: "youtube",
  },
  {
    title: "Test: Rapid Fire 1 Minute @ Each of 5 Spots",
    description:
      "How many 3's can you hit in 1 minute at each of the 5 Spots? (1 minute per Spot for 5 total minutes of shooting).",
    url: "https://youtu.be/KCWyUBX_dEA",
    type: "youtube",
  },
  {
    title: "Test: Wiper Shooting",
    description:
      "Elbow to Short Corner (30 Seconds), Elbow to Elbow (30 seconds), Elbow to Short Corner (30 seconds). Can do from both Mid Range and 3. One ball, one rebounder.",
    url: "https://youtu.be/u1_T3XCc4Fg",
    type: "youtube",
  },
  {
    title: "Test: 3 Minute 3's",
    description:
      "One ball, One rebounder. How many 3's can you make in 3 minutes without shooting the same shot back to back?",
    url: "https://youtu.be/ndmiCPQQkqg",
    type: "youtube",
  },
  {
    title: "Test: 3 in a Row 5 Spots",
    description: "How long does it take to make 3 shots in a row from the designated 5 spots?",
    url: "https://youtu.be/EfQlr_tI45I",
    type: "youtube",
  },
  {
    title: "Test: 2 In a Row 5 Spots",
    description: "Timed Drill: How long does it take you to make 2 in a row at each of the 5 designated spots?",
    url: "https://youtu.be/AIP13rw4MM4",
    type: "youtube",
  },
  {
    title: "Free Throws",
    url: "https://youtu.be/8MyR2srjCRA",
    type: "youtube",
  },
  {
    title: "Ball Raise w/DDS",
    url: "https://youtu.be/gDr8U7jcPBw",
    type: "youtube",
  },
  {
    title: "Hang Pull-ups",
    url: "https://youtu.be/vCevvhdSstg",
    type: "youtube",
  },
  {
    title: "Slow Motion Shot w/DDS",
    url: "https://youtu.be/aU7099dyFPk",
    type: "youtube",
  },
  {
    title: "Hip Taps (DDS)",
    url: "https://youtu.be/H8WHzNI5QmQ",
    type: "youtube",
  },
  {
    title: "Pump Fake Side Step",
    url: "https://youtu.be/OrlQuWKVeyo",
    type: "youtube",
  },
  {
    title: "Dribble Hop Fade",
    url: "https://youtu.be/ePPOkNUx5Xo",
    type: "youtube",
  },
  {
    title: "1 Hand Shooting",
    url: "https://youtu.be/ynKn5qjGjIo",
    type: "youtube",
  },
  {
    title: "1 Foot Elevator Drop",
    url: "https://youtu.be/GfbkcbkDai8",
    type: "youtube",
  },
  {
    title: "Spin Out CK",
    url: "https://youtu.be/gx5IBsbizAE",
    type: "youtube",
  },
  {
    title: "Push Out CK",
    url: "https://youtu.be/M3PLmCp0HzQ",
    type: "youtube",
  },
  {
    title: "1 Foot Drop",
    url: "https://youtu.be/M4lm36fCRl0",
    type: "youtube",
  },
  {
    title: "One Position CK",
    url: "https://youtu.be/Yfhx03rzHlU",
    type: "youtube",
  },
  {
    title: "Slide, Spin & Drop",
    url: "https://youtu.be/1FXDMZie6_k",
    type: "youtube",
  },
  {
    title: "Spin Catch Drop 180 Degrees",
    url: "https://youtu.be/FEi5u8GDet0",
    type: "youtube",
  },
  {
    title: "Spin Catch Drop 90 Degrees",
    url: "https://youtu.be/KF5lvzbSvWw",
    type: "youtube",
  },
  {
    title: "Spin Catch Drop",
    url: "https://youtu.be/2dLB2GxlB0U",
    type: "youtube",
  },
  {
    title: "Catch High Keep High (Movement)",
    url: "https://youtu.be/ifx9jriBJXY",
    type: "youtube",
  },
  {
    title: "Catch High Keep High (Stationary)",
    url: "https://youtu.be/jdCqSY8Aeuc",
    type: "youtube",
  },
  {
    title: "Through Legs 1 2 Step",
    url: "https://youtu.be/pGCIBBdaWwA",
    type: "youtube",
  },
  {
    title: "Slow Motion Sits at Basket",
    url: "https://youtu.be/AK_cLu1njb4",
    type: "youtube",
  },
  {
    title: "Slow Motion 1 2 Through At Basket",
    url: "https://youtu.be/1t4EcBATw2M",
    type: "youtube",
  },
  {
    title: "Slow Motion 1 2 Through To Self",
    url: "https://youtu.be/DzPQa8CTfog",
    type: "youtube",
  },
  {
    title: "Slide Into DDS",
    url: "https://youtu.be/FiPiKF-yFoQ",
    type: "youtube",
  },
  {
    title: "Skinny Side Backboard Shots",
    url: "https://youtu.be/LrD4AYYfGlc",
    type: "youtube",
  },
  {
    title: "Pullback With Drop",
    url: "https://youtu.be/PWx6QMVkpSs",
    type: "youtube",
  },
  {
    title: "Pullback 1-2 BIG Step",
    url: "https://youtu.be/gqB58jtQW94",
    type: "youtube",
  },
  {
    title: "Pullback 90:10 Cliff Walk",
    url: "https://youtu.be/Jz1EMP8RAYc",
    type: "youtube",
  },
  {
    title: "High Ball Drop",
    url: "https://youtu.be/kLPEfrqsjFs",
    type: "youtube",
  },
  {
    title: "Drops into Slow Motion 1 2 Through At Basket",
    url: "https://youtu.be/yY9nJTVq2hg",
    type: "youtube",
  },
  {
    title: "Drops Into Shots At Basket",
    url: "https://youtu.be/p0A0Z24KdgQ",
    type: "youtube",
  },
  {
    title: "Drop with Floor Tap",
    url: "https://youtu.be/DpDxPdoohMQ",
    type: "youtube",
  },
  {
    title: "Drop 1 2 Through With Stop",
    url: "https://youtu.be/3pWmSvIxW9k",
    type: "youtube",
  },
  {
    title: "Dribble 1 2 Step",
    url: "https://youtu.be/KL4c73-bQtg",
    type: "youtube",
  },
  {
    title: "Dribble 1 2 Step With Pass Fake",
    url: "https://youtu.be/6h1MW001STk",
    type: "youtube",
  },
  {
    title: "Dribble 1 2 Step With Ball Raise",
    url: "https://youtu.be/_ZrtYpCtqGA",
    type: "youtube",
  },
  {
    title: "Dribble 1 2 Step Angle",
    url: "https://youtu.be/DSvf748Ytz0",
    type: "youtube",
  },
  {
    title: "DDS",
    url: "https://youtu.be/l7MaNd5R_5g",
    type: "youtube",
  },
  {
    title: "DDS Fake Pass",
    url: "https://youtu.be/kDuO22lK9sw",
    type: "youtube",
  },
  {
    title: "DDS Angle",
    url: "https://youtu.be/iL1QhxcaqPM",
    type: "youtube",
  },
  {
    title: "Forward 1 Position Jog",
    url: "https://youtu.be/x7kWKcet2GE",
    type: "youtube",
  },
  {
    title: "Cliff Walk (1 Position)",
    url: "https://youtu.be/IZ_7upkQ8cE",
    type: "youtube",
  },
  {
    title: "Cliff Walk With Turn (1 Position)",
    url: "https://youtu.be/kL3pvx_n-QQ",
    type: "youtube",
  },
  {
    title: "Ball Raises",
    url: "https://youtu.be/lI_i5xv1VNY",
    type: "youtube",
  },
  {
    title: "Backwards 1 Position Jog",
    url: "https://youtu.be/Guqy8iooJng",
    type: "youtube",
  },
  {
    title: "Backboard Flat Side Shots",
    url: "https://youtu.be/1hslMfG-F08",
    type: "youtube",
  },
  {
    title: "180 Degree Dribble Turns",
    url: "https://youtu.be/Kz5NgM9F5m8",
    type: "youtube",
  },
  {
    title: "180 Degree 1 Position Turn",
    url: "https://youtu.be/ZQF2SCsKwA0",
    type: "youtube",
  },
  {
    title: "90 Degree Dribble Turns",
    url: "https://youtu.be/s4GpK2WOdx8",
    type: "youtube",
  },
  {
    title: "90 Degree 1 Position Turn",
    url: "https://youtu.be/m0_2l_L_khc",
    type: "youtube",
  },
  {
    title: "2x Through Legs 1 2 Step",
    url: "https://youtu.be/QKG1oSizuaU",
    type: "youtube",
  },
  {
    title: "1 2 Step With Drop",
    url: "https://youtu.be/3JwG2NdsmMU",
    type: "youtube",
  },
  {
    title: "1 2 Step With Drop and Turn",
    url: "https://youtu.be/gHJASka2NY4",
    type: "youtube",
  },
  {
    title: "1 2 Through with Stop At Basket",
    url: "https://youtu.be/bQ49FuN5dnA",
    type: "youtube",
  },
  {
    title: "1 2 Through to Self",
    url: "https://youtu.be/Yq3aKUnhhD4",
    type: "youtube",
  },
  {
    title: "Pass it to the Basket",
    url: "https://youtu.be/j6q-hDPr5VU",
    type: "youtube",
  },
  {
    title: "1 2 Through",
    url: "https://youtu.be/0t2i7OYeWKc",
    type: "youtube",
  },
  {
    title: "Shoot the Line",
    url: "https://youtu.be/YGyu7HBtk3s",
    type: "youtube",
  },
  {
    title: "Backboard Flat Shots",
    url: "https://youtu.be/bPZNr7iItnE",
    type: "youtube",
  },
  {
    title: "Backboard Skinny Shots",
    url: "https://youtu.be/U-I576autFs",
    type: "youtube",
  },
  {
    title: "One Hand Pull Backs",
    url: "https://youtu.be/_9xbKNbJ4ag",
    type: "youtube",
  },
  {
    title: "Layering in the Guide Hand",
    url: "https://youtu.be/DkxGrcmp22M",
    type: "youtube",
  },
  {
    title: "Pull Back Drill",
    url: "https://youtu.be/dnEtw2fKVIw",
    type: "youtube",
  },
  {
    title: "Form Shooting With Guide Hand Slide",
    url: "https://youtu.be/o1gQlfPGFWE",
    type: "youtube",
  },
  {
    title: "Backwards Step Catches",
    url: "https://youtu.be/rR6wAqjKkPA",
    type: "youtube",
  },
  {
    title: "Elbow Slides - Movement",
    url: "https://youtu.be/5mDhYd9gVYA",
    type: "youtube",
  },
  {
    title: "Wide Stance Shots",
    url: "https://youtu.be/QHhBWyY-TDg",
    type: "youtube",
  },
  {
    title: "Roll Up Drill",
    url: "https://youtu.be/-c7kfpIkccg",
    type: "youtube",
  },
  {
    title: "Wrist Flips",
    url: "https://youtu.be/APahSa0JDAk",
    type: "youtube",
  },
  {
    title: "Wrist Flips With Spin Out",
    url: "https://youtu.be/um55Ud55RX8",
    type: "youtube",
  },
  {
    title: "Wrist Flips Off the Dribble",
    url: "https://youtu.be/R8I-ciJn0F0",
    type: "youtube",
  },
  {
    title: "One Hand Pick Up Off Dribble",
    url: "https://youtu.be/aAiUxXsAO6Y",
    type: "youtube",
  },
  {
    title: "Adding Guide Hand - One Hand Shots",
    url: "https://youtu.be/ODN3VNnW-90",
    type: "youtube",
  },
  {
    title: "Wrist Flexibility",
    url: "https://youtu.be/3lixCWUf-sY",
    type: "youtube",
  },
  {
    title: "Momentum Shots",
    url: "https://youtu.be/5qBwsCVxtBE",
    type: "youtube",
  },
  {
    title: "Momentum Shots With Hop",
    url: "https://youtu.be/eQxVZujBYwI",
    type: "youtube",
  },
  {
    title: "Momentum Shots With a Pass",
    url: "https://youtu.be/f9CJtpIBn1U",
    type: "youtube",
  },
  {
    title: "Jump Turn Drill",
    url: "https://youtu.be/YMtl1rKZyEY",
    type: "youtube",
  },
  {
    title: "Elbow Reaction Drill",
    url: "https://youtu.be/IEENjOQgL1I",
    type: "youtube",
  },
  {
    title: "Cognitive Slides",
    url: "https://youtu.be/cLSYWM6WaAw",
    type: "youtube",
  },
  {
    title: "Change of Pace - Through Legs",
    url: "https://youtu.be/YtUsfdIlvLM",
    type: "youtube",
  },
  {
    title: "Hip Taps",
    url: "https://youtu.be/nfV1V32dY0c",
    type: "youtube",
  },
  {
    title: "Spot Shooting With A Turn",
    url: "https://youtu.be/rsDikAkmBJs",
    type: "youtube",
  },
  {
    title: "1-2 Step Pull Up with Hand Prep",
    url: "https://youtu.be/7kzJ_pwnXws",
    type: "youtube",
  },
  {
    title: "Box Shots",
    url: "https://youtu.be/FbuwqxmdYhk",
    type: "youtube",
  },
  {
    title: "One Position Hops With Ball Fake",
    url: "https://youtu.be/L2EmrDa2V8E",
    type: "youtube",
  },
  {
    title: "Pivot Drill",
    url: "https://youtu.be/o-J_Q1uPpPY",
    type: "youtube",
  },
  {
    title: "Airborne Shots",
    url: "https://youtu.be/fwDVXUmdHxI",
    type: "youtube",
  },
  {
    title: "Back Foot Push Hand Prep Pump Fake",
    url: "https://youtu.be/Dl78tXlNc_k",
    type: "youtube",
  },
  {
    title: "Backwards 1-2 Step Through Legs",
    url: "https://youtu.be/lQndpV3QHTA",
    type: "youtube",
  },
  {
    title: "Backwards One Dribble One Two Step",
    url: "https://youtu.be/PAU2Z8nuX4o",
    type: "youtube",
  },
  {
    title: "Dribble Step Timing",
    url: "https://youtu.be/8gIUudwQ7-I",
    type: "youtube",
  },
  {
    title: "One Dribble Through Legs",
    url: "https://youtu.be/-n9f_IKCafY",
    type: "youtube",
  },
  {
    title: "One Dribble One Two Step",
    url: "https://youtu.be/QXXN1nycT44",
    type: "youtube",
  },
  {
    title: "Reaction Slides",
    url: "https://youtu.be/0gi36J0Ogmc",
    type: "youtube",
  },
  {
    title: "Shoot to a Partner",
    url: "https://youtu.be/aNqahcyL8AA",
    type: "youtube",
  },
  {
    title: "The Gauntlet",
    url: "https://youtu.be/NEFaxgHsBrk",
    type: "youtube",
  },
  {
    title: "Tap and Back Pedal",
    url: "https://youtu.be/T1FEGuvrAaw",
    type: "youtube",
  },
  {
    title: "Blind Spot Toss",
    url: "https://youtu.be/n0WWBI8Jd5M",
    type: "youtube",
  },
  {
    title: "2 Dribble Elbow Series: Progression 2",
    url: "https://youtu.be/Te1WUDd-LZc",
    type: "youtube",
  },
  {
    title: "Fast, Slow, Fast",
    url: "https://youtu.be/wbzTU-WDePY",
    type: "youtube",
  },
  {
    title: "Free Throw Keys!",
    url: "https://youtu.be/k2jdgybqi5s",
    type: "youtube",
  },
  {
    title: "2 Dribble Baseline To Elbow",
    url: "https://youtu.be/SNJSH58pS7U",
    type: "youtube",
  },
  {
    title: "2 Dribble Hesitation",
    url: "https://youtu.be/LiXzQpXKpaY",
    type: "youtube",
  },
  {
    title: "2 Dribbles Baseline Shot Fake",
    url: "https://youtu.be/BmUMy-7Fv-E",
    type: "youtube",
  },
  {
    title: "2 Dribbles Baseline",
    url: "https://youtu.be/hdg7Tp1E4lU",
    type: "youtube",
  },
  {
    title: "Backwards Step Catch and Shoot",
    url: "https://youtu.be/-5m7GH-2vIg",
    type: "youtube",
  },
  {
    title: "Big Turn Little Turn",
    url: "https://youtu.be/GQDgvWFprpI",
    type: "youtube",
  },
  {
    title: "Catch High Keep High",
    url: "https://youtu.be/gvR57ybVyjY",
    type: "youtube",
  },
  {
    title: "Change of Pace Into Handoff",
    url: "https://youtu.be/UhERV8gLXgU",
    type: "youtube",
  },
  {
    title: "Flare Screens",
    url: "https://youtu.be/eDtsW2NnIfY",
    type: "youtube",
  },
  {
    title: "Jump Turns With A Pass",
    url: "https://youtu.be/9Kp1bb7PNJA",
    type: "youtube",
  },
  {
    title: "Opened Up Pull Backs",
    url: "https://youtu.be/TfgTo2pLAH4",
    type: "youtube",
  },
  {
    title: "Pump Fake With Side Step",
    url: "https://youtu.be/wZc6HBIpspU",
    type: "youtube",
  },
  {
    title: "Reaction Baseline Runs",
    url: "https://youtu.be/Q3948_Cd4N8",
    type: "youtube",
  },
  {
    title: "Shot Drive Drift",
    url: "https://youtu.be/UAvEkeFAhEY",
    type: "youtube",
  },
  {
    title: "Trace the Line Part 2",
    url: "https://youtu.be/LgeefiaUxcw",
    type: "youtube",
  },
]

// Add the Loom explanation videos
export const loomExplanationVideos: VideoEntry[] = [
  {
    title: "Floor Taps With Drop",
    description: "Detailed explanation of floor taps with drops technique",
    url: "https://www.loom.com/share/f88f838cdf6549b2a57546c245d5ad19?sid=172c8f8d-87c0-4263-b3b3-abaf256e0a88",
    type: "loom",
  },
  {
    title: "Pulback with Drop",
    description: "Explanation of pullback drops technique",
    url: "https://www.loom.com/share/cc2bdc2e1cc44d85885223b72616f3c2?sid=59fa0f44-4b9f-4bd5-bc88-eb0bebe89f96",
    type: "loom",
  },
  {
    title: "Skinny Side Backboard Shots",
    description: "Detailed explanation of skinny side backboard shots",
    url: "https://www.loom.com/share/fa09d201855a4095b248614f045011a4?sid=499c3be3-4e70-4736-a940-c76ab53080f9",
    type: "loom",
  },
  {
    title: "Flat Side Backboard Shots",
    description: "Explanation of flat side backboard shots technique",
    url: "https://www.loom.com/share/28a4410a6dd44181afc93f46d927c846?sid=c0f17c33-4af6-4980-96be-4a5449d8b141",
    type: "loom",
  },
  {
    title: "Slow Motion 1-2-Thru @ Hoop",
    description: "Detailed explanation of slow motion 1-2-thru at the hoop",
    url: "https://www.loom.com/share/8ffcd2b6e1ed476b8ee78999d3b9d76c?sid=e81ab663-b9c7-459b-8a34-db267427f396",
    type: "loom",
  },
  {
    title: "1-2-Thru With Stop at Hoop",
    description: "Explanation of 1-2-thru with stop at the hoop",
    url: "https://www.loom.com/share/7ffdb0c461804b059b08a29dca438475?sid=18781a51-d59b-4ede-8646-b92a1dc8dcda",
    type: "loom",
  },
  {
    title: "1-2-Thru Slow Mo (self)",
    description: "Detailed explanation of slow motion 1-2-thru to yourself",
    url: "https://www.loom.com/share/186d8d9d36a346c79dd4017d885d1a38?sid=6c03fb9d-ca6f-423d-9e5d-b19c01212696",
    type: "loom",
  },
  {
    title: "1-2-Thru (self)",
    description: "Explanation of 1-2-thru to yourself technique",
    url: "https://www.loom.com/share/eca7e1a469704367840d2563e33f2d39?sid=be4134dd-64a0-431b-bda7-cb5140c87a10",
    type: "loom",
  },
  {
    title: "Shoot Until I Miss 2 in a Row 5 Spots",
    description: "Explanation of the 'Shoot Until I Miss 2 in a Row 5 Spots' drill",
    url: "https://www.loom.com/share/200ee43d68834a3c8e6a24c2cf8c4ad0?sid=d9c8ece1-c3e1-44fd-a30c-980588c59f4f",
    type: "loom",
  },
  {
    title: "Full Court Threes",
    description: "Detailed explanation of full court threes drill",
    url: "https://www.loom.com/share/a0b56827b38b4d2c9692abf1722ceb91?sid=829863bd-4e4b-4a17-b3f9-7935b42ae827",
    type: "loom",
  },
  {
    title: "Ball Raises",
    description: "Explanation of ball raises technique",
    url: "https://www.loom.com/share/6afe71447c7a4e569c761e5b4d1f65f3?sid=27a93b27-ebe8-4d20-af51-838863e1e696",
    type: "loom",
  },
  {
    title: "High Ball Drop",
    description: "Detailed explanation of high ball drop technique",
    url: "https://www.loom.com/share/a9ac6e63cf7f452896dfbad1f75d58d5?sid=f97a42a0-9dda-425b-8479-b5824a3138f4",
    type: "loom",
  },
  {
    title: "Cliff Walk With Pullback",
    description: "Explanation of cliff walk with pullback technique",
    url: "https://www.loom.com/share/286c805699c44c9fb80ee9560638c350?sid=65dc93f7-ef31-4b3e-87de-f391d5a4de8e",
    type: "loom",
  },
  {
    title: "DDS Fake Pass",
    description: "Detailed explanation of DDS fake pass technique",
    url: "https://www.loom.com/share/9af14e8d27224bfbadb4b4a9a639e78b?sid=febfcbf1-b7e1-4175-846a-9e20fe784c85",
    type: "loom",
  },
  {
    title: "DDS Angle",
    description: "Explanation of DDS angle technique",
    url: "https://www.loom.com/share/73538d2dfeab4875b5290d5c0dc36a6b?sid=f17d959b-8a07-4fb7-9213-b2a09060ae70",
    type: "loom",
  },
  {
    title: "Dribble 1-2-Step With Pass Fake",
    description: "Detailed explanation of dribble 1-2-step with pass fake",
    url: "https://www.loom.com/share/444b2cd5e7354abd9f5c4a11d4c827f4?sid=582d8d94-315d-486b-9d5c-72da97ac2199",
    type: "loom",
  },
  {
    title: "Spin Out With Wrist Flip",
    description: "Explanation of spin out with wrist flip technique",
    url: "https://www.loom.com/share/39143ff58d7a4114aa33f5bdc002fcbc?sid=abc409a5-0b9d-48ca-a54b-b7a6c322d0df",
    type: "loom",
  },
  {
    title: "Spin Out CK",
    description: "Detailed explanation of spin out CK technique",
    url: "https://www.loom.com/share/7f05af1ab7694502a6a231700acbef47?sid=63a18141-6132-4968-8751-cae1d510be09",
    type: "loom",
  },
  {
    title: "1x Thru Legs",
    description: "Explanation of 1x through legs technique",
    url: "https://www.loom.com/share/0544b6c3b53248d887d66f1196cd1a9e",
    type: "loom",
  },
  {
    title: "Spin Catch Drop 180 Degrees",
    description: "Detailed explanation of spin catch drop 180 degrees technique",
    url: "https://www.loom.com/share/0fc0e975d48c4c338e7a52538491e345",
    type: "loom",
  },
  {
    title: "2x Through Legs",
    description: "Explanation of 2x through legs technique",
    url: "https://www.loom.com/share/133eabef0b594b1f96ef7ed8b7bf581a",
    type: "loom",
  },
  {
    title: "Baseline Sprint With Drop",
    description: "Detailed explanation of baseline sprint with drop technique",
    url: "https://www.loom.com/share/1243ef7e3fc648ccbdadb7f57001405d",
    type: "loom",
  },
  {
    title: "Alternate Footwork Spot Shots",
    description: "Explanation of alternate footwork spot shots technique",
    url: "https://www.loom.com/share/1590b812b4a14154b5ccb9f55437c6e1",
    type: "loom",
  },
  {
    title: "Push Out CK",
    description: "Detailed explanation of push out CK technique",
    url: "https://www.loom.com/share/1449208fe1ea46d48a38d247b9f9c8fc",
    type: "loom",
  },
  {
    title: "90 Degree 1-2 Step",
    description: "Explanation of 90 degree 1-2 step technique",
    url: "https://www.loom.com/share/1590325e81284ac18645fc3e591b597c",
    type: "loom",
  },
  {
    title: "Foward Hop",
    description: "Detailed explanation of forward hop technique",
    url: "https://www.loom.com/share/17cbd3bfcc07493a90880e0cbce1d256",
    type: "loom",
  },
  {
    title: "1-2 Step Catch and Shoot Sprints",
    description: "Explanation of 1-2 step catch and shoot sprints technique",
    url: "https://www.loom.com/share/19501b2923174200ab7719ed72e2291d",
    type: "loom",
  },
  {
    title: "Catch High Keep High Movement",
    description: "Detailed explanation of catch high keep high movement technique",
    url: "https://www.loom.com/share/1e4fa446117d4ee3bbeaaba3f2039232",
    type: "loom",
  },
  {
    title: "1-2 Step With Angle",
    description: "Explanation of 1-2 step with angle technique",
    url: "https://www.loom.com/share/1f7c8f6b121040309854789c9b6886e1",
    type: "loom",
  },
  {
    title: "1 Position 90 Degree Turn",
    description: "Detailed explanation of 1 position 90 degree turn technique",
    url: "https://www.loom.com/share/204c79e7a42641c29743339a5ad636e9",
    type: "loom",
  },
  {
    title: "Spin Catch Drop 90 Degree Turn",
    description: "Explanation of spin catch drop 90 degree turn technique",
    url: "https://www.loom.com/share/302ca50fc2aa41e8a88cd4386361416a",
    type: "loom",
  },
  {
    title: "Outside Foot Catch",
    description: "Detailed explanation of outside foot catch technique",
    url: "https://www.loom.com/share/3db5615b3b8c40038d06ccb06f70da93",
    type: "loom",
  },
  {
    title: "2 Speed Dribbled From Half Court",
    description: "Explanation of 2 speed dribbles from half court technique",
    url: "https://www.loom.com/share/3b1fb44e855b488c8a416b7d50dd2125",
    type: "loom",
  },
  {
    title: "Floor Taps- Range Week",
    description: "Detailed explanation of floor taps for range week",
    url: "https://www.loom.com/share/32c3c51f8b104c529fb8d682730fc741",
    type: "loom",
  },
  {
    title: "Catch and Shoot with Drop Range",
    description: "Explanation of catch and shoot with drop range technique",
    url: "https://www.loom.com/share/2f674cb120ff4a1ea8879af13a2406fa",
    type: "loom",
  },
  {
    title: "Bounce Through Range",
    description: "Detailed explanation of bounce through range technique",
    url: "https://www.loom.com/share/2c1b290b4a204b36b1b9a07b2c8861d6",
    type: "loom",
  },
  {
    title: "Hang Dribble",
    description: "Explanation of hang dribble technique",
    url: "https://www.loom.com/share/2483094e98c84e288772f6446d8208bc",
    type: "loom",
  },
  {
    title: "Momentum Shots Range",
    description: "Detailed explanation of momentum shots for range",
    url: "https://www.loom.com/share/24083487d1674f159d9c146b3fd4dbb3",
    type: "loom",
  },
  {
    title: "DDS From Range (With Hip Tap)",
    description: "Explanation of DDS from range with hip tap technique",
    url: "https://www.loom.com/share/229d365e7ef0462981c9deedf28263a7",
    type: "loom",
  },
  {
    title: "Jab Phase II",
    description: "Detailed explanation of jab phase II technique",
    url: "https://www.loom.com/share/22250066bf9144c9a77daacfbaa0252d",
    type: "loom",
  },
  {
    title: "DDS With Stop",
    description: "Explanation of DDS with stop technique",
    url: "https://www.loom.com/share/21d66926fccf46c0b3905e355aa51515",
    type: "loom",
  },
  {
    title: "Dribble Turns (Balance)",
    description: "Detailed explanation of dribble turns for balance",
    url: "https://www.loom.com/share/1f3b98847513413381de2c73630b9263",
    type: "loom",
  },
  {
    title: "Jab Series 1-3",
    description: "Explanation of jab series 1-3 technique",
    url: "https://www.loom.com/share/1b09300033a74e3d8078ed01044339c7",
    type: "loom",
  },
  {
    title: "Rollouts",
    description: "Detailed explanation of rollouts technique",
    url: "https://www.loom.com/share/8c542f7c619f44adb86317b334983112",
    type: "loom",
  },
  {
    title: "Backward Catch and Shoot",
    description: "Explanation of backward catch and shoot technique",
    url: "https://www.loom.com/share/773d38c14cf843b4b71be83f29cdd208",
    type: "loom",
  },
  {
    title: "Pump Fake Side Step",
    description: "Detailed explanation of pump fake side step technique",
    url: "https://www.loom.com/share/71fbef0c9b22431288e8b82f3ea0c854",
    type: "loom",
  },
  {
    title: "Catch and Shoot with Pass Fake",
    description: "Explanation of catch and shoot with pass fake technique",
    url: "https://www.loom.com/share/6d1ae1b324074e92aa5c679ae2ff0767",
    type: "loom",
  },
  {
    title: "2 Dribble Jump Turns",
    description: "Detailed explanation of 2 dribble jump turns technique",
    url: "https://www.loom.com/share/6139895da0ca42c4a3a385c8bf03435b",
    type: "loom",
  },
  {
    title: "Dribble Hop Fade",
    description: "Explanation of dribble hop fade technique",
    url: "https://www.loom.com/share/5ba3da47eb614ba880bded8f3c5077b2",
    type: "loom",
  },
  {
    title: "Jab Phase I",
    description: "Detailed explanation of jab phase I technique",
    url: "https://www.loom.com/share/5b406fd3e9794e3d805023ea8a8e1931",
    type: "loom",
  },
  {
    title: "Momentum Shots With Drop- Range",
    description: "Explanation of momentum shots with drop for range",
    url: "https://www.loom.com/share/58e0881d462549fbb7230a3905f2fc20",
    type: "loom",
  },
  {
    title: "1-2 Step Off Dribble with Stop",
    description: "Detailed explanation of 1-2 step off dribble with stop technique",
    url: "https://www.loom.com/share/52c2b7fa69004935b32c733e7b078f70",
    type: "loom",
  },
  {
    title: "180 DDS",
    description: "Explanation of 180 DDS technique",
    url: "https://www.loom.com/share/4735cadb61e44d69851b7e07a72d664e",
    type: "loom",
  },
  {
    title: "Foward Backward Hops",
    description: "Detailed explanation of forward backward hops technique",
    url: "https://www.loom.com/share/3e93d76fa3ae43609c3154eb5eb4c407",
    type: "loom",
  },
  {
    title: "180 Degree Dribble Turns",
    description: "Explanation of 180 degree dribble turns technique",
    url: "https://www.loom.com/share/41f7723d44564dbaace6f0787909a676",
    type: "loom",
  },
  {
    title: "1 Position Drops",
    description: "Detailed explanation of 1 position drops technique",
    url: "https://www.loom.com/share/55ba165574444dadbe01829afaf420a8",
    type: "loom",
  },
  {
    title: "Cliff Walk with 90 Degree Turn",
    description: "Explanation of cliff walk with 90 degree turn technique",
    url: "https://www.loom.com/share/61298e91e9c94cdaa53262b40fc76d59",
    type: "loom",
  },
  {
    title: "Slide into DDS",
    description: "Detailed explanation of slide into DDS technique",
    url: "https://www.loom.com/share/66b0f9cbc9c046d593b9d205869b248a",
    type: "loom",
  },
  {
    title: "1-2 Step 1 Position 180 Degree Turn",
    description: "Explanation of 1-2 step 1 position 180 degree turn technique",
    url: "https://www.loom.com/share/78f37ee3d6e84bd08e66d4331e774c6d",
    type: "loom",
  },
  {
    title: "Slide Spin Catch and Shoot",
    description: "Detailed explanation of slide spin catch and shoot technique",
    url: "https://www.loom.com/share/7c7f6a86ec504be0afe3077be78e5666",
    type: "loom",
  },
  {
    title: "Sits at Basket",
    description: "Explanation of sits at basket technique",
    url: "https://www.loom.com/share/883f23926e914926904964a5fec2522d",
    type: "loom",
  },
  {
    title: "Catch High Keep High",
    description: "Detailed explanation of catch high keep high technique",
    url: "https://www.loom.com/share/8a1dd9c5c2eb4117963129bbb92fc2db",
    type: "loom",
  },
  {
    title: "Backward Hops",
    description: "Explanation of backward hops technique",
    url: "https://www.loom.com/share/98f49550e2dd40f2bea661b004155908",
    type: "loom",
  },
  {
    title: "Forward 1 Position Job",
    description: "Detailed explanation of forward 1 position job technique",
    url: "https://www.loom.com/share/9f4f62dfbbbe456ca0aafbce5e6c98cf",
    type: "loom",
  },
  {
    title: "1-2 Step With Pullback",
    description: "Explanation of 1-2 step with pullback technique",
    url: "https://www.loom.com/share/aac965ccab0342418fe46fd1efbb92b8",
    type: "loom",
  },
  {
    title: "One Position CK",
    description: "Detailed explanation of one position CK technique",
    url: "https://www.loom.com/share/ad1cded7d1644e75bbdc3f156da6ef88",
    type: "loom",
  },
  {
    title: "Backward Jog 1 Position",
    description: "Explanation of backward jog 1 position technique",
    url: "https://www.loom.com/share/bb49971f97d64a1b9f09d658697d81f5",
    type: "loom",
  },
  {
    title: "Spin Catch Drop",
    description: "Detailed explanation of spin catch drop technique",
    url: "https://www.loom.com/share/bd1d57b758c545cc8245df581dfb6f0c",
    type: "loom",
  },
  {
    title: "DDS With Ball Raise",
    description: "Explanation of DDS with ball raise technique",
    url: "https://www.loom.com/share/bdc01d3ff5d04408bd5df7ed53cd3a65",
    type: "loom",
  },
  {
    title: "Wrist Flips Off Dribble",
    description: "Detailed explanation of wrist flips off dribble technique",
    url: "https://www.loom.com/share/c3c8747eeb414572974e22d636583f55",
    type: "loom",
  },
  {
    title: "1 Position Drops For Range",
    description: "Explanation of 1 position drops for range technique",
    url: "https://www.loom.com/share/c5dab82aecb24fbfb4ea5a848f77215d",
    type: "loom",
  },
  {
    title: "180 Elevator Turns Off Dribble",
    description: "Detailed explanation of 180 elevator turns off dribble technique",
    url: "https://www.loom.com/share/b7e2e565acbf4c50af706cc51cc09e8a",
    type: "loom",
  },
  {
    title: "Sprint Into Slide to Corner",
    description: "Explanation of sprint into slide to corner technique",
    url: "https://www.loom.com/share/b293129eafdf4e7bbeb861528c2994cd",
    type: "loom",
  },
  {
    title: "Steph Curry Transition",
    description: "Detailed explanation of Steph Curry transition technique",
    url: "https://www.loom.com/share/a9a8aee959fa4fb3891ba2d622072942",
    type: "loom",
  },
  {
    title: "180 1-2 Step Off Dribble",
    description: "Explanation of 180 1-2 step off dribble technique",
    url: "https://www.loom.com/share/a960fc8f09784967917d0e9c90845649",
    type: "loom",
  },
  {
    title: "Ghost Screen Into Back Pedal",
    description: "Detailed explanation of ghost screen into back pedal technique",
    url: "https://www.loom.com/share/a5346d4c2c714c3083fd0bd3cba25260",
    type: "loom",
  },
  {
    title: "Transition Fade to Wing",
    description: "Explanation of transition fade to wing technique",
    url: "https://www.loom.com/share/8d3e7d9d95824e3c8a9346e7d6a73071",
    type: "loom",
  },
  {
    title: "90 Degree Elevator Drops Off Dribble",
    description: "Detailed explanation of 90 degree elevator drops off dribble technique",
    url: "https://www.loom.com/share/f52e91f4f7534ad48b9977e3630bad88",
    type: "loom",
  },
  {
    title: "Elbow Push Out With Stop",
    description: "Explanation of elbow push out with stop technique",
    url: "https://www.loom.com/share/ec59c61f369742aa85640cc76200393f",
    type: "loom",
  },
  {
    title: "Sprint to Corner",
    description: "Detailed explanation of sprint to corner technique",
    url: "https://www.loom.com/share/e4dd8ddd488744b3943d0cfc37edda16",
    type: "loom",
  },
  {
    title: "Catch and Shoot Off Drop",
    description: "Explanation of catch and shoot off drop technique",
    url: "https://www.loom.com/share/dce8d44057e94dbe9fd42f8bfb30ed11",
    type: "loom",
  },
  {
    title: "Jump Turns Off Pass",
    description: "Detailed explanation of jump turns off pass technique",
    url: "https://www.loom.com/share/d6a5615974d34b7db8678caf25748cd4",
    type: "loom",
  },
  {
    title: "Sprint to Top of Key with Drop",
    description: "Explanation of sprint to top of key with drop technique",
    url: "https://www.loom.com/share/d5c38a5f965647ecba05fd65fd16702c",
    type: "loom",
  },
  {
    title: "Rollout with Slides",
    description: "Detailed explanation of rollout with slides technique",
    url: "https://www.loom.com/share/d5aba99af2a346b5aa612ee4ae6b47ae",
    type: "loom",
  },
  {
    title: "Lateral Movement into DDS",
    description: "Explanation of lateral movement into DDS technique",
    url: "https://www.loom.com/share/d51f51c396bb47c8970d45bb40d23b09",
    type: "loom",
  },
  {
    title: "Elbow Push Outs No Stop",
    description: "Detailed explanation of elbow push outs no stop technique",
    url: "https://www.loom.com/share/cdbdd9e46c724e4e8f7f3da602f3f4c3",
    type: "loom",
  },
  {
    title: "1 Foot Elevator Drops",
    description: "Explanation of 1 foot elevator drops technique",
    url: "https://www.loom.com/share/ca9226b09bee4e6991982c951c61a63a",
    type: "loom",
  },
  {
    title: "1 Foot Drops",
    description: "Detailed explanation of 1 foot drops technique",
    url: "https://www.loom.com/share/c989b4ee86db4af28b27d1a21b4a8ad9",
    type: "loom",
  },
  {
    title: "Jab Phase III",
    description: "Explanation of jab phase III technique",
    url: "https://www.loom.com/share/c89ae76b40524dfba175638cbbbc88cd",
    type: "loom",
  },
  {
    title: "Dribble 1-2 Step With Ball Raise",
    description: "Detailed explanation of dribble 1-2 step with ball raise technique",
    url: "https://www.loom.com/share/c8cc788d30394e2ca05783bf8d3a0d27",
    type: "loom",
  },
  {
    title: "DDS",
    description: "Explanation of DDS technique",
    url: "https://www.loom.com/share/c9ea8ad1dcac4c8da28b9af8cfadd1df",
    type: "loom",
  },
  {
    title: "Dribble 1-2 Step",
    description: "Detailed explanation of dribble 1-2 step technique",
    url: "https://www.loom.com/share/e374c360ab7b4a679f88b796614d3ed0",
    type: "loom",
  },
  {
    title: "180 Degree 1 Position Step Drop",
    description: "Explanation of 180 degree 1 position step drop technique",
    url: "https://www.loom.com/share/e524f597293c4f1fbd60d8d0b4f56bc4",
    type: "loom",
  },
  {
    title: "Backward Forward Hops",
    description: "Detailed explanation of backward forward hops technique",
    url: "https://www.loom.com/share/e93229cc36f448599cb93b56a0f3fba1",
    type: "loom",
  },
  {
    title: "180 Degree 1 Position Turn",
    description: "Explanation of 180 degree 1 position turn technique",
    url: "https://www.loom.com/share/f07f6a880c8a4ca4a4caf75d4dc92c17",
    type: "loom",
  },
  {
    title: "90 Degree Dribble Turns",
    description: "Detailed explanation of 90 degree dribble turns technique",
    url: "https://www.loom.com/share/f0e3fafd81e84a268eb3d7653aa87b58",
    type: "loom",
  },
]

// Combine the YouTube and Loom videos for the complete database
export const allVideos = [...videoDatabase, ...loomExplanationVideos]
